//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : MainPlane.h
//  @ Date : 2011/8/30
//  @ Author : 
//
//


#if !defined(_ENEMYMAINPLANE_H)
#define _ENEMYMAINPLANE_H

#include "DX11\Vertex.h"
#include "DX11\TextureManager.h"
#include "math\OgreVector3.h"
#include "algo\nway.h"
#include "ball\straight.h"
#include "towers\tower.h"
#include "MainPlane.h"

class EnemyMainPlane : public MainPlane
{
public:
	Ogre::Vector3	targetPos;
	float		secPerBullet;
	int		launchCounts;
public:
	EnemyMainPlane(){}
	void Update(float dt);
	int  UpdateTower(float dt);
protected:
	void UpdateDataToDraw();
};

#endif  //_MAINPLANE_H
