//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : MainPlane.h
//  @ Date : 2011/8/30
//  @ Author : 
//
//


#if !defined(_MAINPLANE_H)
#define _MAINPLANE_H

#include "DX11\Vertex.h"
#include "DX11\TextureManager.h"
#include "math\OgreVector3.h"
#include "algo\nway.h"
#include "ball\straight.h"
#include "towers\tower.h"
#include "path\LinearLine.h"
#include "path\BezierCurve.h"
#include "path\BsplineCurve.h"
#include "path\HSplineCurve.h"

class MainPlane
{
public:
	DXVertex	m_pic;
	Texture_Sptr	m_texture;
	Ogre::Vector3	m_position;

	float		m_angle;
	int		m_hp;
	int		m_w, m_h;
	Towers		m_Towers;
	HSplineCurve ll;
public:
	MainPlane()
	{
		ll.AddPoint(2, Ogre::Vector3(0,0,0));
		ll.AddPoint(3, Ogre::Vector3(500,500,0));
		ll.AddPoint(4, Ogre::Vector3(400,400,0));
		ll.AddPoint(5, Ogre::Vector3(400,500,0));
		ll.AddPoint(6, Ogre::Vector3(600,600,0));
		ll.AddPoint(7, Ogre::Vector3(600,700,0));
	}
	void Update(float dt);
	int  UpdateTower(float dt);
protected:
	void UpdateDataToDraw();
};

#endif  //_MAINPLANE_H
