//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : MainPlane.h
//  @ Date : 2011/8/30
//  @ Author : 
//
//


#if !defined(_MAINPLANE_H)
#define _MAINPLANE_H
#include "math\OgreVector3.h"
#include "DX11\Vertex.h"
#include "DX11\TextureManager.h"


class MainPlane {
public:
	DXVertex	m_pic;
	Texture_Sptr	m_texture;
	Ogre::Vector3	m_position;
	float		m_angle;
	int		m_hp;
	int		m_w, m_h;
	void Update();
	void UpdateDataToDraw()
	{
		m_pic.position.x = m_position.x;
		m_pic.position.y = m_position.y;
		m_pic.position.z = 0;
		m_pic.angle = m_angle;
		m_pic.size.x = (float)m_w;
		m_pic.size.y = (float)m_h;
	}
};

#endif  //_MAINPLANE_H
