//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : LinearLine.h
//  @ Date : 2011/9/3
//  @ Author : 
//
//


#if !defined(_LINEARLINE_H)
#define _LINEARLINE_H

#include "PathInterpolater.h"

class LinearLine : public PathInterpolater
{
public:
	Ogre::Vector3 GetValue(float time);
	static Ogre::Vector3 CalcStraightPos(const Ogre::Vector3& p1, const Ogre::Vector3& p2, float scalar)
	{
		Ogre::Vector3 out = p1 * (1.0f-scalar) + p2 * scalar;
		return out;
	}
};

#endif  //_LINEARLINE_H
