//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : MainPlane.h
//  @ Date : 2011/8/30
//  @ Author : 
//
//


#if !defined(_ENEMYMAINPLANE_H)
#define _ENEMYMAINPLANE_H

#include "DX11\Vertex.h"
#include "DX11\TextureManager.h"
#include "math\OgreVector3.h"
#include "algo\nway.h"
#include "ball\straight.h"
#include "towers\tower.h"

class EnemyMainPlane
{
public:
	DXVertex	m_pic;
	Texture_Sptr	m_texture;
	Ogre::Vector3	m_position;
	Polygon2D	m_Polygon2D;

	float		m_angle;
	int		m_hp;
	int		m_w, m_h;
	Towers		m_Towers;

	Ogre::Vector3	m_targetPos;
public:
	inline EnemyMainPlane() {}
	void Update(float dt);
	int  UpdateTower(float dt);
protected:
	void UpdateDataToDraw();
};

#endif  //_MAINPLANE_H
