//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : MainPlane.cpp
//  @ Date : 2011/8/30
//  @ Author : 
//
//

#include "EnemyMainPlane.h"
#include "DX11/InputState.h"
#include "algo/sgmath.h"
#include "DX11/InitDirect3DApp.h"
#include "global.h"
#include "DX11/WaveSound.h"

void EnemyMainPlane::Update(float dt) 
{
	Ogre::Vector3 trans = Ogre::Vector3(0, 0, 0);
	m_position += trans;
	UpdateTower(dt);
	UpdateDataToDraw();
}

int EnemyMainPlane::UpdateTower(float dt)
{
	return MainPlane::UpdateTower(dt);
}

void EnemyMainPlane::UpdateDataToDraw()
{
// 	m_pic.position.x = m_position.x;
// 	m_pic.position.y = m_position.y;
// 	m_pic.position.z = 0;
// 	m_pic.angle = m_angle;
// 	m_pic.size.x = (float)m_w;
// 	m_pic.size.y = (float)m_h;
	MainPlane::UpdateDataToDraw();
}


