//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : BullectManager.cpp
//  @ Date : 2011/8/31
//  @ Author : 
//
//


#include "BullectManager.h"

void BullectManager::AddBullet() 
{

}

void BullectManager::Update()
{

}

