//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : bullet.cpp
//  @ Date : 2011/8/30
//  @ Author : 
//
//


#include "bullet.h"

void bullet::Update() {

}

