//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : BullectManager.h
//  @ Date : 2011/8/31
//  @ Author : 
//
//


#if !defined(_BULLECTMANAGER_H)
#define _BULLECTMANAGER_H


class BullectManager {
public:
	void AddBullet();
	void Update();
};

#endif  //_BULLECTMANAGER_H
