//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : BezierCurve.h
//  @ Date : 2011/9/3
//  @ Author : 
//
//


#if !defined(_BEZIERCURVE_H)
#define _BEZIERCURVE_H

#include "PathInterpolater.h"

class BezierCurve : public PathInterpolater
{
public:
	Ogre::Vector3 GetValue(float time);
	inline Ogre::Vector3 CalcBezierCurvePos(const Ogre::Vector3& start, const Ogre::Vector3& cnt1,
		const Ogre::Vector3& cnt2, const Ogre::Vector3& end, float Scalar)
	{
		Ogre::Vector3 out = start * (1.0f - Scalar) * (1.0f - Scalar) * (1.0f - Scalar) +
			cnt1 * 3.0f * Scalar * (1.0f - Scalar) * (1.0f - Scalar) +
			cnt2 * 3.0f * Scalar * Scalar * (1.0f - Scalar) +
			end * Scalar * Scalar * Scalar;
		return out;
	}
};

#endif  //_BEZIERCURVE_H
