//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Stage.h
//  @ Date : 2011/9/6
//  @ Author : 
//
//


#if !defined(_STAGE_H)
#define _STAGE_H
#include "towers/tower.h"
#include "planes/EnemyPlane.h"
#include "bullets/bullet.h"
#include "algo/nway.h"
#include "algo/RandomWay.h"
#include "algo/StraightWay.h"
#include "algo/SwirlWay.h"
#include "algo/TrajectoryAnimator.h"
#include "ball/straight.h"
#include "ball/split.h"
#include "ball/homing.h"
#include "ball/gravity.h"
#include "ball/delay.h"

class Stage
{
public:
	void AddEnmyPlane();
	void GetTimeToGenerateEnmyPlane();
};

#endif  //_STAGE_H
