//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : LoadStage.h
//  @ Date : 2011/9/6
//  @ Author : 
//
//


#if !defined(_LOADSTAGE_H)
#define _LOADSTAGE_H


class LoadStage {
public:
	void LoadStage();
};

#endif  //_LOADSTAGE_H
