//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : LoadStage.cpp
//  @ Date : 2011/9/6
//  @ Author : 
//
//


#include "LoadStage.h"



void LoadStage::LoadNewStage( std::string path, Stage& toStage )
{
	m_LuaCell.InputLuaFile(path.c_str());
	toStage.AddEnmyPlane();
}
