//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : LoadStage.cpp
//  @ Date : 2011/9/6
//  @ Author : 
//
//


#include "LoadStage.h"



void LoadStage::LoadNewStage( std::string path, Stage& toStage )
{
	m_Lua.InputLuaFile(path.c_str());
	for (int i=1;;++i)
	{
		if (m_Lua.CheckNotNil("stage/%d/time", i))
		{
			float time = (float)m_Lua.getLua<double>("stage/%d/time", i);
			
			toStage.AddEnmyPlane();
		}
		else
			break;
	}
	
}
