//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Stage.cpp
//  @ Date : 2011/9/6
//  @ Author : 
//
//


#include "Stage.h"

void Stage::AddEnmyPlane()
{

}

void Stage::GetTimeToGenerateEnmyPlane()
{

}

