//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Stage.h
//  @ Date : 2011/9/6
//  @ Author : 
//
//


#if !defined(_STAGE_H)
#define _STAGE_H


class Stage {
public:
	void AddEnmyPlane();
	void GetTimeToGenerateEnmyPlane();
};

#endif  //_STAGE_H
